name: RedstoneDisabler
version: '${project.version}'
main: me.zivush.redstonedisabler.RedstoneDisabler
api-version: '26.1.2'
commands:
  redstonedisabler:
    description: Reload the RedstoneDisabler configuration
    usage: /redstonedisabler reload
    permission: redstonedisabler.reload
    aliases: [ rd ]
permissions:
  redstonedisabler.reload:
    description: Allows reloading the RedstoneDisabler configuration
    default: op